RUNNER-1
T-mFive/Runner pull request #3
Opened 2022-07-17 13:09 UTC by loosq

### RUNNER-1 https://trello.com/c/aLTRoSnU

Добавил странички:

- Форум (за исключением внутренних страниц, их ещё подизайню и добавлю попозже, так же не реализован функционал добавления тем)
- Главная
- Лидерборд

Так же добавил цсс переменные (`var(--...)`), для темизации в последующем

2022-07-17 13:30 UTC, veniameen approved these changes

2022-07-18 15:57 UTC, AMorozov-web requested changes

2022-07-18 15:57 UTC, AMorozov-web commented on src/components/navigation/types.ts
> +export type Props = FC<NavigationProps>;
Лучше размести в компоненте

2022-07-18 15:57 UTC, AMorozov-web commented on src/components/pages/forum/Forum.tsx
> +import forumLogo from './../../../../static/images/forum-logo.png';
Лучше перевести лого в `svg` и импортировать как компонент, либо сделать папку `assets` и импортить из нее, соответственно подправив вебпак

2022-07-19 08:42 UTC, loosq commented on src/components/navigation/types.ts
> +export type Props = FC<NavigationProps>;
В файловой структуре проекта кажется типы были в отдельном файле

2022-07-19 16:26 UTC, TonyBNK approved these changes

2022-07-19 17:40 UTC, AMorozov-web commented on src/components/navigation/types.ts
> +export type Props = FC<NavigationProps>;
Типы бывают разные. Есть типы базовые, типа Nullable, есть типы, описывающие какую то Dto. Их можно и нужно хранить отдельно. Типы описывающие пропсы компонента лучше хранить в компоненте

2022-07-19 18:30 UTC, loosq commented on src/components/navigation/types.ts
> +export type Props = FC<NavigationProps>;
ok

2022-07-19 18:30 UTC, loosq commented on src/components/pages/forum/Forum.tsx
> +import forumLogo from './../../../../static/images/forum-logo.png';
убрал картинку

2022-07-19 18:39 UTC, AMorozov-web approved these changes

2022-07-19 18:42 UTC, merged