Runner 4
T-mFive/Runner pull request #6
Opened 2022-07-21 16:04 UTC by veniameen

2022-07-21 16:28 UTC, AMorozov-web requested changes

2022-07-21 16:28 UTC, AMorozov-web commented on src/components/pages/Game/Game.tsx
> +    if (canvasRef !== null) {
`if (canvasRef.current)` и не нужен будет as

2022-07-21 16:28 UTC, AMorozov-web commented on src/components/pages/Game/Game.tsx
> +  const [score, setScore] = useState(0)
Лучше сразу указывать тип значения

2022-07-21 16:28 UTC, AMorozov-web commented on src/components/pages/Game/Game.tsx
> +      {console.log(score)}
Не забудь потом удалить

2022-07-21 16:28 UTC, AMorozov-web commented on src/components/pages/Game/core/common/Hero.tsx
> +    protected game: any,
CoreType

2022-07-22 03:47 UTC, AMorozov-web approved these changes

2022-07-23 08:17 UTC, TonyBNK commented on src/components/pages/Game/Game.tsx
> +
отступы между импортами не обязательны

2022-07-23 08:17 UTC, TonyBNK commented on src/components/pages/Game/Game.tsx
> +import React, { memo, FC, useState, useEffect } from 'react'
прогонись, пожалуйста, линтерами по всему проекту, он должен расставить точки с запятой,
а то получается, что где-то есть, а где-то нет

2022-07-23 18:40 UTC, TonyBNK approved these changes

2022-07-24 15:54 UTC, loosq approved these changes

2022-07-25 09:05 UTC, merged