Deploy
T-mFive/Runner pull request #7
Opened 2022-07-26 07:30 UTC by TonyBNK

2022-07-27 18:55 UTC, AMorozov-web requested changes

2022-07-27 18:55 UTC, AMorozov-web commented on .eslintrc.json
> +        "no-console": "off",
Лучше оставить `warn`

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/complex/Modal/Modal.tsx
> +import { CrossIcon } from 'components/base';
Для иконок лучше тогда создать отдельный файл

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/complex/Modal/Modal.tsx
> +export const Modal: React.FC<Props> = React.memo((
Типизация через FC накладывает на компонент ограничения, например компонент нельзя сделать дженериком

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/Game.tsx
>  export const Game: FC<unknown> = memo(() => {
Если у компонента нет пропсов `memo` не работает, а только тормозит первую загрузку компонента

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/common/Obstacle.tsx
>          this.spawnTimer = this.initialSpawnTimer = 180;
Так лучше не писать - не очевидно и читается не очень

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/common/UI.tsx
> +            // eslint-disable-next-line no-unused-expressions
Исправь на if else - не понадобится выключать правило

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/core.tsx
> +        // eslint-disable-next-line no-restricted-globals
Укажи, на какой элемент добавляется обработчик, и не понадобится выключать правило

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/core.tsx
> +            // eslint-disable-next-line no-return-assign
Исправь на  `(e: KeyboardEvent) => {this.keys[e.code] = true}`

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/core.tsx
>  window.requestAnimationFrame = (func: FrameRequestCallback): any => {
Тут можно вместо any добавить void

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Game/core/scenes/GameScene.tsx
>                  setTimeout(() => (this.pause = !this.pause), 0);
setTimeout(() => {this.pause = !this.pause}, 0);

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Leaderboard/Leaderboard.tsx
>  export const Leaderboard: React.FC<unknown> = React.memo(() => (
Убери memo

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Login/Login.tsx
>  export const Login: React.FC<unknown> = React.memo(() => {
Убери memo

2022-07-27 18:55 UTC, AMorozov-web commented on src/components/pages/Registration/Registration.tsx
>  export const Registration: React.FC<unknown> = React.memo(() => {
Убери memo

2022-07-29 14:47 UTC, loosq approved these changes

2022-08-01 15:02 UTC, veniameen approved these changes

2022-08-02 18:04 UTC, AMorozov-web approved these changes

2022-08-02 18:04 UTC, merged